# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4fd11515f80bfa2068456e556d023608a19a78b1804d8934ae3dc421a8be1f3d68856b38d4a5d65d091dc491e427a2ecc9477469c8cf8c6a6db3597bcf3b54b

test:
  secret_key_base: 4ec758ede8526ea0e758629ff6e9ac76ce614ff5ca98e352b3a344b05e0626bd4e85d9905e74eee8ebbe093bf977e6390ba1f38cda08fa14688dda567ec93658

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
